# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Il7qLrtoZwfRgU80K0AFMHMgpivDqNkL
"""

!pip install pyTelegramBotAPI

#библиотеки, которые загружаем из вне
import telebot
TOKEN = '6386342606:AAGd8Iin3An3YPVpkX7VdFD5e7dpFWyGQsQ'

from telebot import types

bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start'])
def welcome(message):
	sti = open('welcome.webp', 'rb')
	bot.send_sticker(message.chat.id, sti)

	#клавиатура
	markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
	item1 = types.KeyboardButton("Контакты")
	item2 = types.KeyboardButton("Расписание")
	item3 = types.KeyboardButton("Ресурсы преподавателей")

	markup.add(item1, item2, item3)

	bot.send_message(message.chat.id, "Приветствую, {0.first_name}!".format(message.from_user, bot.get_me()),
		parse_mode='html', reply_markup=markup)

#назначаем действие для клавиатуры
@bot.message_handler(content_types=['text'])
def lalala(message):
	if message.chat.type == 'private':
		if message.text == 'Контакты':
			bot.send_message(message.chat.id, 'https://ckstr.ru/?page_id=295')
		elif message.text == 'Расписание':
			bot.send_message(message.chat.id, 'http://schedule.ckstr.ru/')
		elif message.text == 'Ресурсы преподавателей':
			bot.send_message(message.chat.id, 'https://docs.google.com/spreadsheets/d/1DSEI1FXMVTMRPf2E168JUUN0RZCjP-R3SaemohnN3zU/edit#gid=327390739')
		else:
			bot.send_message(message.chat.id, 'Не знаю что ответить😢')


bot.polling(none_stop=True)









#https://core.telegram.org/bots/api#available-methods